# Generated by Django 5.2.7 on 2025-10-31 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button', models.BooleanField(default=False)),
                ('isHighlighted', models.BooleanField(default=False)),
                ('lastPressed', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
