# Generated by Django 5.2.7 on 2025-12-10 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HighlightButton', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highlight',
            name='button',
        ),
        migrations.AddField(
            model_name='highlight',
            name='spotid',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
