# Generated by Django 5.2.7 on 2025-10-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglotlocater', '0002_building_distance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Housing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housingName', models.CharField(max_length=100)),
                ('closestParking', models.CharField(max_length=100)),
                ('distance', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
    ]
