# Generated by Django 5.2.7 on 2025-12-04 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglotlocater', '0003_housing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='buildingName',
            field=models.CharField(max_length=100),
        ),
    ]
