# Generated by Django 5.2.7 on 2025-12-05 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglotlocater', '0004_alter_building_buildingname'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='parkingLotLat',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='building',
            name='parkingLotLong',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
