# Generated by Django 5.2.7 on 2025-12-05 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglotlocater', '0005_building_parkinglotlat_building_parkinglotlong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='parkingLotLat',
            field=models.DecimalField(decimal_places=6, default=10.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='building',
            name='parkingLotLong',
            field=models.DecimalField(decimal_places=6, default=10.0, max_digits=9),
        ),
    ]
