# Generated by Django 5.2.7 on 2025-12-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglotlocater', '0006_alter_building_parkinglotlat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='parkingLotLat',
            field=models.DecimalField(decimal_places=13, default=0.0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='building',
            name='parkingLotLong',
            field=models.DecimalField(decimal_places=13, default=0.0, max_digits=16),
        ),
    ]
