# Generated by Django 5.2.7 on 2025-10-30 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleInput', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classinput',
            old_name='time',
            new_name='endTime',
        ),
        migrations.RemoveField(
            model_name='classinput',
            name='duration',
        ),
        migrations.AddField(
            model_name='classinput',
            name='startTime',
            field=models.TimeField(default='00:00'),
            preserve_default=False,
        ),
    ]
