# Generated by Django 6.0 on 2025-12-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleInput', '0002_rename_time_classinput_endtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classinput',
            name='closest_parking',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
