# Generated by Django 6.0 on 2025-12-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleInput', '0003_classinput_closest_parking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classinput',
            name='closest_parking',
        ),
        migrations.AddField(
            model_name='classinput',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classinput',
            name='location',
            field=models.CharField(choices=[('Adams Center', 'Adams Center'), ('Adams Hall', 'Adams Hall'), ('Anne and Henry Zarrow Hall', 'Anne and Henry Zarrow Hall'), ('Armory', 'Armory'), ('Beatrice Carr Wallace Old Science Hall', 'Beatrice Carr Wallace Old Science Hall'), ('Bizzell Memorial Library', 'Bizzell Memorial Library'), ('Boomer Outreach Building', 'Boomer Outreach Building'), ('Boyd House', 'Boyd House'), ('Buchanan Hall', 'Buchanan Hall'), ('Bud Wilkinson House', 'Bud Wilkinson House'), ('Burton Hall', 'Burton Hall'), ('Carnegie Building', 'Carnegie Building'), ('Carpenter Hall', 'Carpenter Hall'), ('Carson Engineering Center', 'Carson Engineering Center'), ('Cate Center 1', 'Cate Center 1'), ('Cate Center 2', 'Cate Center 2'), ('Cate Center 3', 'Cate Center 3'), ('Cate Center 4', 'Cate Center 4'), ('Cate Center Dining Hall', 'Cate Center Dining Hall'), ('Catlett Music Center', 'Catlett Music Center'), ('Chemistry Annex', 'Chemistry Annex'), ('Chemistry Building', 'Chemistry Building'), ('Collings Hall', 'Collings Hall'), ('Collums Building', 'Collums Building'), ('Copeland Hall', 'Copeland Hall'), ('Couch Center', 'Couch Center'), ('Couch Restaurants', 'Couch Restaurants'), ('Cross', 'Cross'), ('Dale Hall', 'Dale Hall'), ('Dale Hall Tower', 'Dale Hall Tower'), ('David L. Boren Hall (The Honors College)', 'David L. Boren Hall (The Honors College)'), ('Devon Energy Hall', 'Devon Energy Hall'), ('Donald W. Reynolds Performing Arts Center', 'Donald W. Reynolds Performing Arts Center'), ('Dunham College', 'Dunham College'), ('Dunham College and Headington College Dining Halls', 'Dunham College and Headington College Dining Halls'), ('Ellison Hall', 'Ellison Hall'), ('Engineering Laboratory', 'Engineering Laboratory'), ('Evans Hall', 'Evans Hall'), ('Everest Training Center', 'Everest Training Center'), ('Facilities Management Complex', 'Facilities Management Complex'), ('Farzaneh Hall', 'Farzaneh Hall'), ('Felgar Hall', 'Felgar Hall'), ('Fine Arts Center', 'Fine Arts Center'), ('Fred Jones Jr. Art Center', 'Fred Jones Jr. Art Center'), ('Fred Jones Jr. Museum of Art', 'Fred Jones Jr. Museum of Art'), ('Gallogly ', 'Gallogly '), ('Gaylord Family-Oklahoma Memorial Stadium', 'Gaylord Family-Oklahoma Memorial Stadium'), ('Gaylord Hall', 'Gaylord Hall'), ('George Lynn Cross Hall', 'George Lynn Cross Hall'), ('Goddard Health Center', 'Goddard Health Center'), ('Gould Hall', 'Gould Hall'), ('Headington College', 'Headington College'), ('Headington Hall', 'Headington Hall'), ('Henderson-Tolson Cultural Center', 'Henderson-Tolson Cultural Center'), ('Jacobs Track and Field Facility', 'Jacobs Track and Field Facility'), ('Jacobson Hall (The OU Visitor Center)', 'Jacobson Hall (The OU Visitor Center)'), ('Jim Thorpe Multicultural Center', 'Jim Thorpe Multicultural Center'), ('Kaufman Hall', 'Kaufman Hall'), ('Lin Hall', 'Lin Hall'), ('Lissa and Cy Wagner Hall', 'Lissa and Cy Wagner Hall'), ('McCasland Field House', 'McCasland Field House'), ('Monnet Hall', 'Monnet Hall'), ('Mosier Indoor Athletic Facility', 'Mosier Indoor Athletic Facility'), ('Murray Case Sells Swim Center', 'Murray Case Sells Swim Center'), ('Nielsen Hall', 'Nielsen Hall'), ('Noble Electron Microscopy Laboratory', 'Noble Electron Microscopy Laboratory'), ('Nuclear Engineering Laboratory', 'Nuclear Engineering Laboratory'), ('Observatory and Landscape Department', 'Observatory and Landscape Department'), ('OCCE James P. Pappas Administration Building', 'OCCE James P. Pappas Administration Building'), ('OCCE McCarter Hall of Advanced Studies', 'OCCE McCarter Hall of Advanced Studies'), ('OCCE Thurman J. White Forum Building', 'OCCE Thurman J. White Forum Building'), ('Oklahoma Memorial Union', 'Oklahoma Memorial Union'), ('Old Faculty Club', 'Old Faculty Club'), ('OU Bookstore', 'OU Bookstore'), ('Parking Services Office', 'Parking Services Office'), ('Physical Sciences Center', 'Physical Sciences Center'), ('Price Hall', 'Price Hall'), ('Rawl Engineering Practice Facility', 'Rawl Engineering Practice Facility'), ('Richards Hall', 'Richards Hall'), ('Robertson Hall', 'Robertson Hall'), ('Sarkeys Energy Center', 'Sarkeys Energy Center'), ('Sarkeys Fitness Center', 'Sarkeys Fitness Center'), ('Sooner Card Office', 'Sooner Card Office'), ('Sooner Suites', 'Sooner Suites'), ('Sutton Hall', 'Sutton Hall'), ('The Switzer Center', 'The Switzer Center'), ('Wagner Dining Facility', 'Wagner Dining Facility'), ('Walker Center', 'Walker Center'), ('Whitehand Hall', 'Whitehand Hall')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='classinput',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
