# Generated by Django 6.0 on 2025-12-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleInput', '0004_remove_classinput_closest_parking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classinput',
            name='days',
            field=models.CharField(default='', max_length=15),
        ),
    ]
