# Generated by Django 5.2.7 on 2025-10-31 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datadashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('format', models.CharField(choices=[('csv', 'CSV'), ('json', 'JSON')], max_length=10)),
                ('lot_id', models.CharField(blank=True, max_length=100)),
                ('rows_count', models.PositiveIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ParkingLot',
        ),
    ]
