# Generated by Django 4.2.25 on 2025-12-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Housing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housingName', models.CharField(max_length=100)),
                ('closestParking', models.CharField(max_length=100)),
                ('distance', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
    ]
