# Generated by Django 4.2.25 on 2025-12-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housinglotlocater', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housing',
            name='name',
        ),
        migrations.AddField(
            model_name='housing',
            name='closestParking',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='housing',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='housing',
            name='housingName',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
