# Generated by Django 6.0 on 2025-12-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housinglotlocater', '0002_remove_housing_name_housing_closestparking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='closestParking',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='housing',
            name='housingName',
            field=models.CharField(max_length=100),
        ),
    ]
