# Generated by Django 4.2.25 on 2025-12-04 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parkingLotHistory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkinghistory',
            name='available_spots',
        ),
        migrations.RemoveField(
            model_name='parkinghistory',
            name='lot_name',
        ),
        migrations.RemoveField(
            model_name='parkinghistory',
            name='occupied_spots',
        ),
        migrations.AddField(
            model_name='parkinghistory',
            name='building_name',
            field=models.CharField(default='building_name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkinghistory',
            name='user',
            field=models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
