# Generated by Django 4.2.25 on 2025-12-05 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parkingLotHistory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkinghistory',
            old_name='lot_name',
            new_name='building_name',
        ),
        migrations.RemoveField(
            model_name='parkinghistory',
            name='available_spots',
        ),
        migrations.RemoveField(
            model_name='parkinghistory',
            name='occupied_spots',
        ),
        migrations.AddField(
            model_name='parkinghistory',
            name='closest_lot',
            field=models.TextField(default='Unknown'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkinghistory',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkinghistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
