# Generated by Django 5.2.7 on 2025-10-07 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglotlocater', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
