# Generated by Django 5.2.7 on 2025-10-30 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableLots',
            fields=[
                ('lot_id', models.AutoField(primary_key=True, serialize=False)),
                ('lot_name', models.CharField(max_length=100)),
                ('total_spaces', models.PositiveIntegerField()),
                ('available_spaces', models.PositiveIntegerField()),
                ('status', models.CharField(default='Open', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
