# Generated by Django 5.2.7 on 2025-12-02 18:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availableLots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablelots',
            name='available_spaces',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='availablelots',
            name='lot_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='availablelots',
            name='total_spaces',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
